## Reading Data from Different Sources

In [1]:
import pandas as pd
from io import StringIO

Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df = pd.read_json(StringIO(Data))

In [2]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [3]:
df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [4]:
df.to_json(orient="index")

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [5]:
df.to_json(orient="records")

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [6]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [7]:
df.to_csv("wine.csv")

In [8]:
url = "https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

pd.read_html(url)

[                                          Bank Name               City  \
 0                                         Nano Banc             Irvine
 1                       Tioga-Franklin Savings Bank       Philadelphia
 2                               Small Business Bank             Lenexa
 3     Kentland Federal Savings and Loan Association           Kentland
 4           Community Bank and Trust - West Georgia           LaGrange
 5                 Metropolitan Capital Bank & Trust            Chicago
 6                      The Santa Anna National Bank         Santa Anna
 7                              Pulaski Savings Bank            Chicago
 8                The First National Bank of Lindsay            Lindsay
 9             Republic First Bank dba Republic Bank       Philadelphia
 10                                    Citizens Bank           Sac City
 11                         Heartland Tri-State Bank            Elkhart
 12                              First Republic Bank      San Francisco
 13                                   Signature Bank           New York
 14                              Silicon Valley Bank        Santa Clara
 15                                Almena State Bank             Almena
 16                       First City Bank of Florida  Fort Walton Beach
 17                             The First State Bank      Barboursville
 18                               Ericson State Bank            Ericson
 19                 City National Bank of New Jersey             Newark
 20                                    Resolute Bank             Maumee
 21                            Louisa Community Bank             Louisa
 22                             The Enloe State Bank             Cooper
 23              Washington Federal Bank for Savings            Chicago
 24  The Farmers and Merchants State Bank of Argonia            Argonia

             State   Cert                              Acquiring Institution  \
 0      California  58590                                       Sunwest Bank
 1    Pennsylvania  33802  Second Federal Savings and Loan Association of...
 2          Kansas  25744           The Farmers State Bank of Oakley, Kansas
 3         Indiana  28722                                      Kentland Bank
 4         Georgia  25796                                        Anchor Bank
 5        Illinois  57488                            First Independence Bank
 6           Texas   5520                          Coleman County State Bank
 7        Illinois  28611                                    Millennium Bank
 8        Oklahoma   4134                             First Bank & Trust Co.
 9    Pennsylvania  27332                  Fulton Bank, National Association
 10           Iowa   8758                          Iowa Trust & Savings Bank
 11         Kansas  25851                             Dream First Bank, N.A.
 12     California  59017                          JPMorgan Chase Bank, N.A.
 13       New York  57053                                Flagstar Bank, N.A.
 14     California  24735                First–Citizens Bank & Trust Company
 15         Kansas  15426                                        Equity Bank
 16        Florida  16748                          United Fidelity Bank, fsb
 17  West Virginia  14361                                     MVB Bank, Inc.
 18       Nebraska  18265                         Farmers and Merchants Bank
 19     New Jersey  21111                                    Industrial Bank
 20           Ohio  58317                                 Buckeye State Bank
 21       Kentucky  58112                  Kentucky Farmers Bank Corporation
 22          Texas  10716                                 Legend Bank, N. A.
 23       Illinois  30570                                 Royal Savings Bank
 24         Kansas  17719                                        Conway Bank

           Closing Date  Fund  Sort ascending
 0   September 25, 2026                 10555
 1      August 21, 2026                 10554
 2        July 17, 2026                 10553
 3        July 10, 2026                 10552
 4          May 1, 2026                 10551
 5     January 30, 2026                 10550
 6        June 27, 2025                 10549
 7     January 17, 2025                 10548
 8     October 18, 2024                 10547
 9       April 26, 2024                 10546
 10    November 3, 2023                 10545
 11       July 28, 2023                 10544
 12         May 1, 2023                 10543
 13      March 12, 2023                 10540
 14      March 10, 2023                 10539
 15    October 23, 2020                 10538
 16    October 16, 2020                 10537
 17       April 3, 2020                 10536
 18   February 14, 2020                 10535
 19    November 1, 2019                 10534
 20    October 25, 2019                 10533
 21    October 25, 2019                 10532
 22        May 31, 2019                 10531
 23   December 15, 2017                 10530
 24    October 13, 2017                 10529  ]

In [9]:
df[0]

0      1
1      1
2      1
3      1
4      1
      ..
173    3
174    3
175    3
176    3
177    3
Name: 0, Length: 178, dtype: int64

In [10]:
import requests

url = "https://en.wikipedia.org/wiki/Mobile_country_code"

headers = {
    "User-Agent": "Mozilla/5.0 (compatible; PandasLearning/1.0)"
}

response = requests.get(url, headers=headers, timeout=30)
response.raise_for_status()

tables = pd.read_html(StringIO(response.text), match="Country", header=0)

df = tables[0]
df.head()

,Mobile country code,Country,ISO 3166,Mobile network codes,National MNC authority,Remarks
0,289,A Abkhazia,GE-AB,List of mobile network codes in Abkhazia,NaN,MCC is not listed by ITU
1,412,Afghanistan,AF,List of mobile network codes in Afghanistan,NaN,NaN
2,276,Albania,AL,List of mobile network codes in Albania,NaN,NaN
3,603,Algeria,DZ,List of mobile network codes in Algeria,NaN,NaN
4,544,American Samoa (United States of America),AS,List of mobile network codes in American Samoa,NaN,NaN

In [14]:
df_excel = pd.read_excel("data.xlsx")

In [15]:
df_excel.to_pickle("df_excel")

In [16]:
pd.read_pickle("df_excel")

    Name  Age
0  Krish   32
1   Jack   34
2   John   31